AWS_ACCESS_KEY: "AKIAI42CGKLHRY55QSYA"
AWS_SECRET_KEY: "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"
AWS_BUCKET: whatwedolockedout


# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
production:
  AWS_ACCESS_KEY: "AKIAI42CGKLHRY55QSYA"
  AWS_SECRET_KEY: "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"
  AWS_BUCKET: whatwedolockedout
